spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  instance:
    prefer-ip-address: true

  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 3000
    response-cache-auto-expiration-in-seconds: 180
    response-cache-update-interval-ms: 3000

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${BIOSAN_EUREKA:http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka}
